"""Feedbackrating

Revision ID: 7540b4e774f2
Revises: b6a5e10070a4
Create Date: 2024-07-07 11:05:58.160628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7540b4e774f2'
down_revision: Union[str, None] = 'b6a5e10070a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
